### ISSUE TITLE
demo project fails to compile

### ISSUE THREAD

**Issue by neurolabusc** [Alexey-T/Python-for-Lazarus#15]
I downloaded the latest Python-4-Lazarus (with 64 commits) and opened on my Ubuntu 18.04 system with Lazarus 2.1.0 SVN 62040M GTK2 and FPC 3.0.4. I opened the demo_lazarus project and attempted to compile. The function FormMain.pas Py_s1 generates the error
  
`formmain.pas(58,16) Error: UTF-8 code greater than 65535 found`

This line looks like this
  `S0: string = 'begin.𠏽𠏽𠏽𠏽𠏽.end'; `

1. If I change string to UnicodeString it still fails to compile.
2. If I remove the funny looking (Unicode) characters of this line I can compile the project.
3. If I change the line to [Unicode](https://wiki.freepascal.org/Unicode_Support_in_Lazarus) `S0: UnicodeString = '╩';` is compiles.

Not sure if this is simply a problem with Github encoding of text files or not.

Thanks for supporting this terrific project.

**Comment by Alexey-T** [comment]
Fixed the demo. It was FPC 3.0.4 issue , 3.3 is ok
