### ISSUE TITLE
No rule to make target 'cleanide ide'.  Stop.

### ISSUE THREAD

**Issue by TheChymera** [Alexey-T/Python-for-Lazarus#17]
I am trying to include this package in lazarus 2.0.2, via:

```
./lazbuild -B --lazarusdir="." --pcp="../lazarus-package-config" --build-ide=Gentoo --add-package ../Python-for-Lazarus-11110be6034c7e39daa2cf7154ad04bba0e1cb04/python4lazarus/python4lazarus_package.lpk
```

and I get `No rule to make target 'cleanide ide'.  Stop.`. Here is the full [build.log](https://github.com/Alexey-T/Python-for-Lazarus/files/4023046/build.log).

Any idea what I can do?

**Comment by Alexey-T** [comment]
I don't support lazbuild program, so you may ask as Lazarus forum.
