### ISSUE TITLE
Demo01-06

### ISSUE THREAD

**Issue by mamin27** [Alexey-T/Python-for-Lazarus#20]
Thanks Alex, You can add also demo01, it was also changed. Ok I will remove project1. I let you know.

**Comment by mamin27** [comment]
It is prepared now. Demo07 is not running correctly. AddDelphiMethod has some issue. Scripts was tested at Ubuntu19.04. Maybe it needs to be fixed for MS, Mac.

**Comment by Alexey-T** [comment]
Test demo7 first and make it OK on Win/Lin/Mac.

**Comment by mamin27** [comment]
Ok
