### ISSUE TITLE
Regression in master branch

### ISSUE THREAD

**Issue by neurolabusc** [Alexey-T/Python-for-Lazarus#21]
I am using Lazarus trunk (SVN 62843) and fpc (3.0.4+dfsg-23 [2019/11/25]) with Ubuntu 20.04 daily. I can install and run the current release (2019.12.26) of Python-for-Lazarus just fine. The only change I made to the Demo is to set the location of my Python library:
```
 cPyLibraryLinux = '/usr/lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8.so';
```

However, if I uninstall the lpk and git clone and install the latest master release of Python-for-Lazarus, things do not work as expected. The example demos all fail:
```
Error: Could not open Dll "libpython3.8.so"
Python could not be properly initialized. We must quit.
```
Since the demos have changes, I also recompiled the demo project from the 2019.12.26 release, and it also fails to run when the latest master .lpk is installed.

Conversely, if I install the stable release (2019.12.26) .lpk, I am able to successfully compile and run the demo files included in the more recent master.

There seems to be some regression with the latest master. Thanks again for your support of this terrific package!

**Comment by neurolabusc** [comment]
The code that fails is in `PythonENgine.pas`:

```
procedure TDynamicDll.LoadDll;
begin
   OpenDll(DllPath + DllName);
end;   
```
Here is one fix:

```
procedure TDynamicDll.LoadDll;
begin
  OpenDll(IncludeTrailingPathDelimiter(DllPath) + DllName);
end;   
```
Here is another: 

```
procedure TDynamicDll.LoadDll;
begin
  OpenDll(GetDllPath(DllPath) + DllName);
end; 
```

**Comment by Alexey-T** [comment]
is it better now? i reverted 3 changes in git, made last month.

**Comment by neurolabusc** [comment]
Yes, master now works on my system. Thanks!
