### ISSUE TITLE
LongInt size on non-Windows 64bit platforms

### ISSUE THREAD

**Issue by pyscripter** [Alexey-T/Python-for-Lazarus#22]
In FPC LongInt is always 4bytes.
In Delphi LongInt is 4bytes on Windows (32 and 64bits) but 8 bytes on MacOS and Linux 64bits.
Same is true about Python and gcc's long type.

As it stands FPC programs will fail on MacOS and Linux 64bits when they use Python interface functions that have LongInt or LongWord arguments.  (Search for LongInt in PythonEngine.pas).

LongInt should be replaced with a typedef that behaves as Delphi and Python.

**Comment by Alexey-T** [comment]
what type in Delphi is always 32 bit? i will use it in `ifdef fpc`.

**Comment by pyscripter** [comment]
Integer is always 32bit.

But I think you missed my point.  LongInt works fine with Delphi.  
you need something like:
```pascal
{$ifdef fpc}
  {$ifdef mswindows} 
    newtype = integer
  {$else} 
    newtype = NativeInt
  {$endif}
{$else} 
  newtype = LongInt
{$Endif}

```

**Comment by pyscripter** [comment]
```pascal
  {$ifdef mswindows} 
    long = integer
  {$else} 
    long= NativeInt
  {$endif}
```
should work with both delphi and fpc

**Comment by pyscripter** [comment]
By the way I am adding support for MacOS and Linux on the Delphi side.   There will be a number of changes that are relevant to FPC, so do check in a few days.

**Comment by Alexey-T** [comment]
IMO your code above is not ok.
for FPC we need Longint.
for Delphi we need integer (which is always 32bit?)
so ur code is not ok.

**Comment by Alexey-T** [comment]
maybe
{$ifdef fpc} long = longint {$else} long = integer {$endif}
?

http://docwiki.embarcadero.com/RADStudio/Rio/en/Simple_Types_(Delphi)
or maybe use Int32?

**Comment by Alexey-T** [comment]
Platform-independent integer types always have the same size, regardless of what platform you use. Platform-independent integer types include ShortInt, SmallInt, LongInt, Integer, Int64, Byte, Word, LongWord, Cardinal, and UInt64. 
http://docwiki.embarcadero.com/RADStudio/Rio/en/Simple_Types_(Delphi)
so ur comment is not ok.

**Comment by pyscripter** [comment]
I am not sure you understood the issue.
The python c api for certain functions using long in c.  This has been translated as longint in P4D.

The c long is 4 bytes on Windows 32bit and 64bit but 8bit in MacOS and Linux 64bits.
Same for Delphi longint.   So Delphi is OK as it is.  LongInt works fine in Delphi.

The problem is that in fpc longint is always 4 bytes including in MacOs and Linux 64bits.

This is what my suggestion above tries to fix.

**Comment by Alexey-T** [comment]
now I understood. but how CudaText with Python-for-Lazaruus works on Linux x64 and macOS x64? it works ok.

**Comment by pyscripter** [comment]
You probably do not use the relevant API.

**Comment by Alexey-T** [comment]
Maybe you can help? By changing type in needed places to new name. Eg TPyLong.

I will redefine it ltr

**Comment by Alexey-T** [comment]
I fear I can change unneeded places :(

**Comment by pyscripter** [comment]
Will implement it in the pyscripter/Python4Delphi.
