### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by neurolabusc** [Alexey-T/Python-for-Lazarus#25]
Hello,
 The 2020.07.31 included many functions that I used that have been removed from the 2020.10.23 release. Specifically: PyString_AsAnsiString, PyString_FromString, PyInt_FromLong. Was there a reason for their removal? What alternative functions can be used with the new code?

**Comment by Alexey-T** [comment]
sorry, it is so because sync with Python4delphi.
see this topic,
https://github.com/pyscripter/python4delphi/issues/201
you need to use other functions.
https://github.com/pyscripter/python4delphi/issues/207

**Comment by neurolabusc** [comment]
@Alexey-T Thanks for your swift response. I appreciate the desire to synchronize releases. However, the while previous versions have been working for me for years, I can not figure out how to get the latest version to work at all on my MacOS environment. Can you please update the examples in /Demos_Lazarus to illustrate how the new code is supposed to function? At the moment, these Lazarus projects Demo01, Demo06, Demo25, Demo31 have the requirement for the package "P4DLaz" (which does not exist) and do not include a requirement for the "python4lazarus_package". These also require the Windows unit that is not cross-platform. The "python_thread" and "python_console" name the correct package and do not include the Windows unit, but neither one works correctly on my MacOS computer.

I think the following helper functions could support the new and old conversion functions:

```
{$DEFINE NEWPY}
function PyString_AsAnsiString(obj : PPyObject): string;
begin
  {$IFDEF NEWPY}
  result := GetPythonEngine.PyUnicode_AsWideString(obj);
  {$ELSE}
  result := GetPythonEngine.PyString_AsAnsiString(GetPythonEngine.PyTuple_GetItem(Args,i));
  {$ENDIF}
end;

function PyString_FromString(s: string):PPyObject;
begin
  {$IFDEF NEWPY}
  result := GetPythonEngine.PyUnicodeFromString(s);
  {$ELSE}
  result := GetPythonEngine.PyString_FromString(s);
  {$ENDIF}
end;

function PyInt_FromLong(l: integer):PPyObject;
begin
  {$IFDEF NEWPY}
  result:= GetPythonEngine.PyLong_FromLong(l);
  {$ELSE}
  result:= GetPythonEngine.PyInt_FromLong(l);
  {$ENDIF}
end; 
```

However, I am unable to test this as even the simplest script (which works happily with your previous release):
```
print('Hello world')
```
crashes (using the same dylib that works happily with your previous versions):
```
Using preference file PyLib "/System/Library/Frameworks/Python.framework/Versions/Current/lib/libpython2.7.dylib"
Error: could not find symbol "_Py_FalseStruct"
Python could not be properly initialized. We must quit.
Exception at 0000000000000000: EAccessViolation:
```

**Comment by Alexey-T** [comment]
@pyscripter Can you please see the question above, what functions to use? Thanks

**Comment by pyscripter** [comment]
This is not about functions.  

> Using preference file PyLib "/System/Library/Frameworks/Python.framework/Versions/Current/lib/libpython2.7.dylib"

@neurolabusc Your program is trying to use Python 2.7 which is no longer supported.  You should load libpython3.x instead.

**Comment by neurolabusc** [comment]
1. Can the Lazarus demos be updated to work cross platform.
2. Is there a way to detect Python version beyond file name. Many in my field use older Linux and macOS versions that come with Python 2.7 by default.

**Comment by neurolabusc** [comment]
With MacOS BigSur on Apple Silicon, Python2.7 is still the current version. If one installs the Apple Command Line Tools, you can get a arm-native Python3 ( /usr/bin/python3) but this does not include a libpython3*dylib. One can install Python3 with Anaconda, but these must be translated.

 ```
 $ ls /System/Library/Frameworks/Python.framework/Versions/
2.3	2.5	2.6	2.7	Current
$ ls /System/Library/Frameworks/Python.framework/Versions/Current/lib 
libpython2.7.dylib	pkgconfig		python2.7
 file /System/Library/Frameworks/Python.framework/Versions/Current/lib/libpython2.7.dylib
/System/Library/Frameworks/Python.framework/Versions/Current/lib/libpython2.7.dylib: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64e]
/System/Library/Frameworks/Python.framework/Versions/Current/lib/libpython2.7.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
/System/Library/Frameworks/Python.framework/Versions/Current/lib/libpython2.7.dylib (for architecture arm64e):	Mach-O 64-bit dynamically linked shared library arm64e
file /Users/chrisrorden/opt/miniconda3/pkgs/python-3.8.3-h26836e1_1/lib/libpython3.8.dylib 
/Users/chrisrorden/opt/miniconda3/pkgs/python-3.8.3-h26836e1_1/lib/libpython3.8.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```

Likewise, many institutional Linux servers (like the supercomputer at my University) run older Linux where Python2.7 is still standard. 

I understand the desire to have cleaner code, but will allowing my code to be compatible would require users to uninstall the Lazarus4Python package and recompile the IDE with the older version.

**Comment by Alexey-T** [comment]
@neurolabusc Cudatext supports versions up to 3.8, i will fix it ASAP to support 3.9 too.
```
  {$ifdef darwin}
  for N:= 5 to 8 do
  begin
    S:= Format('/Library/Frameworks/Python.framework/Versions/3.%d/lib/libpython3.%d.dylib',
      [N, N]);
    if FileExists(S) then exit(S);
  end;
  exit;
  {$endif}  
```

**Comment by pyscripter** [comment]
@Alexey-T 

>   {$ifdef darwin}
>   for N:= 5 to 8 do
>   begin
>     S:= Format('/Library/Frameworks/Python.framework/Versions/3.%d/lib/libpython3.%d.dylib',
>       [N, N]);
>     if FileExists(S) then exit(S);
>   end;
>   exit;
>   {$endif}

Shall I add the above to P4D?

**Comment by neurolabusc** [comment]
@Alexey-T moving to an Intel Mac where 
   /Library/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7.dylib
exists, and where I use this as the DLL, the sample project
  /demos_lazarus/Python_Console
compiles and launches, but never executes any Python code, even a simple `print(3+2)`. Would it be possible to have at least one working Lazarus demo. It is strange that some of the demos in this repository seem to require the a package from a different repository ([P4DLaz](https://github.com/pyscripter/python4delphi)). I was also unable to get [P4Dlaz](https://github.com/pyscripter/python4delphi/issues/228) to install.

**Comment by Alexey-T** [comment]
@pyscripter 
no, it was code from Cudatext, it 's not for P4D.

**Comment by Alexey-T** [comment]
@neurolabusc to fix in #26, this issue is about functions. you found functions? so solved.

**Comment by neurolabusc** [comment]
Unable to get any of the demo projects to work for the current variations of the Python27-for-Lazarus and P4DLaz, so unable to test any of the functions. I am happy to help test PyInt_FromLong, PyString_FromString functions once working demos are provided. 

The ability to support both Python 2.7 as well as 3.x is important for my applications. Therefore, I have created a fork of  Python-for-Lazarus [2020.07.31](https://github.com/neurolabusc/Python27-for-Lazarus), the last version to support Python 2.7. I did update the demo projects to auto-detect Python 2.7, 3.5-3.9 using the code you provide above. This version includes working functions for PyInt_FromLon and PyString_FromString.

**Comment by Alexey-T** [comment]
@neurolabusc sorry for long delay.
It seems that current demo_console works on all Pythons 3.x (not Py 2.7) on macOS.
because I added Py lib detection in demo_console:
https://github.com/Alexey-T/Python-for-Lazarus/commit/11b25a3f669ffeb01378aed5617c97841fb250ad

**Comment by neurolabusc** [comment]
Thanks. I am closing the issue.

As an aside, it might be worth using the newest version of Python available, changing
```
for N:= 5 to 10 do
```
to read
```
for N:= 11 downto 5 do
```
