### ISSUE TITLE
TPythonEngine.Destroy

### ISSUE THREAD

**Issue by pyscripter** [Alexey-T/Python-for-Lazarus#29]
Question:  Is it really necessary to do it differently in fpc than delphi?

```pascal
destructor TPythonEngine.Destroy;
begin
  LocalVars := nil;
  GlobalVars := nil;
  Destroying;
  Finalize;
{$IFDEF FPC}
  inherited;
{$ENDIF}  // Free our objects
  FClients.Free;
  FInitScript.Free;
  FTraceback.Free;
  FLock.Free;
{$IFNDEF FPC}
  inherited;
{$ENDIF}
end;
```

**Comment by Alexey-T** [comment]
compared 2 versions, only FLock.Free is missing..
![dif](https://user-images.githubusercontent.com/4154978/106376458-97f3f280-63a6-11eb-8fd4-a220b22dbb6f.png)

should I sync with your FLOck? with last your diffs?

**Comment by Alexey-T** [comment]
sync'ed now.

**Comment by pyscripter** [comment]
@Alexey-T The question was about the IFDEFS.

Do we need separate treatment of fpc?  The natural position of the inherited  call is at the end.

**Comment by Alexey-T** [comment]
yes, correct. made the fix, CudaText lives OK with it...

**Comment by z4ziggy** [comment]
This should be reverted since the python lib must be freed prior to the variables. I tried to trace down the culprit but it's a debugging nightmare. The only solution for now for a complete memory cleanup with no memleaks, is to revert this change.

**Comment by Alexey-T** [comment]
@z4ziggy Reverted.

**Comment by pyscripter** [comment]
@z4ziggy @Alexey-T 
Can someone explain to me why "the python lib must be freed prior to the variables"?
Does this affect Delphi as well?

**Comment by Alexey-T** [comment]
I don’t know it…

**Comment by pyscripter** [comment]
Does the fix to the above resolve the memory leaks that @z4ziggy mentioned?

**Comment by Alexey-T** [comment]
i copied pyscripter's fix to Python4Lazarus. z4ziggy can test it.
