### ISSUE TITLE
class exception 'External: SIGSEGV'

### ISSUE THREAD

**Issue by pyscripter** [Alexey-T/Python-for-Lazarus#30]
https://github.com/pyscripter/python4delphi/issues/285

Does this happen with your fork?

**Comment by esperti** [comment]
no, no forks. I installed python4delphi from Lazarus' official online repository.

**Comment by Alexey-T** [comment]
I cannot get the idea- how to repro this? what 'repro'?

**Comment by esperti** [comment]
i meant from lazarus online package manager.
![Screenshot from 2021-02-15 09-27-10](https://user-images.githubusercontent.com/8236249/107922396-3ddf5980-6f70-11eb-96d6-83723c94df7a.png)

**Comment by Alexey-T** [comment]
no feedback, so closing this.
