### ISSUE TITLE
Invalid syntax when compiling the package

### ISSUE THREAD

**Issue by ThaiDat** [Alexey-T/Python-for-Lazarus#33]
Can not install the latest version due to a compile error. Seem because this line is invalid syntax

https://github.com/Alexey-T/Python-for-Lazarus/blob/1b044d8b932189ac159d996e02419602a087dc36/python4lazarus/PythonEngine.pas#L2616

I update full compiler error log:
```
Compile package python4lazarus_package 1.4: Exit code 1, Errors: 2, Hints: 12
...(Hints)...
PythonEngine.pas(2617,17) Error: Procedure or Function expected
PythonEngine.pas(2617,17) Fatal: Syntax error, "identifier" expected but "THREADVAR" found
```

PS: FPC version 3.04, Lazarus version 2.0.4

**Comment by ThaiDat** [comment]
I found that it is a compatibility issue as class threadvar is the new feature introduced in FPC 3.2. I think it would be a lot better to make the new version of the library backward compatible with older versions of the compiler. Anyway, it's my fault that doesn't check for requirements carefully.

**Comment by Alexey-T** [comment]
I don’t know how to replace it - with ifdef of course.
