### ISSUE TITLE
Lazarus crashes while delete components

### ISSUE THREAD

**Issue by RDarkCat** [Alexey-T/Python-for-Lazarus#34]
Add PythonEngine PythonInputOutput Python Module.

Connect PythonInputOutput with PythonEngine.

Select all coimponents with mouse . Press Del. button on keyboard.

Lazarus crashes.

**Comment by Alexey-T** [comment]
Please post this the the lazarus forum,
https://forum.lazarus.freepascal.org/index.php?board=13.0

**Comment by Alexey-T** [comment]
I wrote in the Laz forums, that I cannot repro this. sorry. so cannot fix.
