### ISSUE TITLE
vcruntime for Windows

### ISSUE THREAD

**Issue by neurolabusc** [Alexey-T/Python-for-Lazarus#35]
At the moment, Python-for-Lazarus running on Windows fails to load the Python3*.dll if the computer does not have the file vcruntime140.dll in the system's path. I notice that CudaText includes this dll. 

I would suggest including this library at the same location as the Python3*.dll and explicitly loading it by changing [Line 2911](https://github.com/Alexey-T/Python-for-Lazarus/blob/214f1cf58c339319c8dc3db02aefddafdc0f2f14/python4lazarus/PythonEngine.pas#L2911)

```
    {$ifdef windows}
    S := GetDllPath+'vcruntime140.dll';
    FDLLHandle := Windows.LoadLibrary(PChar(S));
    S := GetDllPath+DllName;
    FDLLHandle := Windows.LoadLibrary(PChar(S));
    {$else}
```

**Comment by Alexey-T** [comment]
I dont like the idea 'to explicitly load it', it's bad practice. Better to add the info somewhere.

**Comment by neurolabusc** [comment]
An alternative would be to add the path of the Python3*.dll to the Windows DLL search path using [SetDllDirectoryA](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setdlldirectorya), that way Windows can find and load the vcruntime DLL if needed:

```
{$ifdef windows}
function  SetDllDirectory(lpPathName: LPCTSTR):LongBool; stdcall; external 'kernel32.dll' name 'SetDllDirectoryA'; //uses add windows,sysutils,
{$endif}
...
SetDllDirectory(PChar(GetDllPath));
```

**Comment by Alexey-T** [comment]
It''s not needed for Py4Lazarus, it is the code for final app. so add it in your app.

**Comment by neurolabusc** [comment]
The Python-for-Lazarus demos_lazarus applications will not run on computers that do not have vcruntime in their system path. The error message provided does not provide the user or developer with any feedback for diagnosis. I would suggest adding it to Python-for-Lazarus, but alternatively you could add it to the demo apps.

I have added the SetDllDirectory solution to the [PythonPascalBridge](https://github.com/neurolabusc/PythonPascalBridge) repository. This is an alternative to Python-for-Lazarus but allows static linking of Python into Linux and macOS executables.

**Comment by Alexey-T** [comment]
But that VS runtime is present, because it’s required for python DLL.
