### ISSUE TITLE
Add license to project

### ISSUE THREAD

**Issue by neurolabusc** [Alexey-T/Python-for-Lazarus#36]
Could you please add a [license to this project](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)? Since this is a fork of [python4delphi](https://github.com/pyscripter/python4delphi), I presume it maintains the MIT License. I realize that files like PythonEngine.pas include a license, but it would be nice to have an explicit license at the top level.

**Comment by Alexey-T** [comment]
Added, thanks.
