### ISSUE TITLE
Error installing from Lazarus Online Package Manager

### ISSUE THREAD

**Issue by 22878120** [Alexey-T/Python-for-Lazarus#38]
I tried to install it in Lazarus from the online package manager, but I got the following error during install...

I'm testing with Lazarus on RaspberryPi 4

```
Compile package python4lazarus_package 1.4: Exit code 1, Errors: 2, Warnings: 1, Hints: 12
.
.
.
PythonEngine.pas(2617,17) Error: Procedure or Function expected
PythonEngine.pas(2617,17) Fatal: Syntax error, "identifier" expected but "THREADVAR" found
```

![image](https://user-images.githubusercontent.com/71804519/138193326-7b668f63-f796-4409-8cbb-d51b646c6e6f.png)

**Comment by Alexey-T** [comment]
@user4martin Do you have an idea how to fix this using conditional defines? TIA!
