### ISSUE TITLE
Command Line Sample

### ISSUE THREAD

**Issue by JacoFourie** [Alexey-T/Python-for-Lazarus#41]
Hi.

Do you have a sample where there is no forms but just command line app. I want to wrap Python code inside Lazarus so users can not read the code. But all samples use GUI forms.

**Comment by Alexey-T** [comment]
I don't have command line example, if Python4Delphi original repo don't have them.

**Comment by JacoFourie** [comment]
OK so are you saying the control can not be use in a command line app only?

**Comment by Alexey-T** [comment]
I think it can be used. In this repo, we have demo program with LCL forms. maybe demo can be rewritten to cmd-line.

**Comment by JacoFourie** [comment]
@Alexey-T if I look at this page at the bottom it shows command line only. But when I include your package in the project the  code will not compile as it has Forms code in it.
https://wiki.freepascal.org/Python4Delphi

![image](https://user-images.githubusercontent.com/17771641/160304864-2ffd353e-f567-41e9-9fa7-db2269414acd.png)

**Comment by JacoFourie** [comment]
I got it working if I use GUI Forms. But I want to run it as non GUI in a terminal.

**Comment by JacoFourie** [comment]
OK I got it working thanks
