### ISSUE TITLE
Error when importing package psycopg2

### ISSUE THREAD

**Issue by JacoFourie** [Alexey-T/Python-for-Lazarus#42]
Hi. 

Hi. I can run simple Python commands from the test program

I have a Python script that connects to a Postgsql DB. The scrip works fine when I run it in Python, but when I embed it in Lazarus I get this error.

```
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: /usr/local/lib/python3.7/dist-packages/psycopg2/_psycopg.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: PyExc_SystemError
[FORMS.PP] ExceptionOccurred 
  Sender=EPyImportError
  Exception=ImportError: /usr/local/lib/python3.7/dist-packages/psycopg2/_psycopg.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: PyExc_SystemError
  Stack trace:
  $00402708  TPYTHONENGINE__RAISEERROR,  line 5452 of ./Sources/Core/PythonEngine.pas
  $00407CD0  TPYTHONENGINE__CHECKERROR,  line 6459 of ./Sources/Core/PythonEngine.pas
  $00401ECC  TPYTHONENGINE__RUN_COMMANDASOBJECTWITHDICT,  line 5259 of ./Sources/Core/PythonEngine.pas
  $00401D18  TPYTHONENGINE__RUN_COMMANDASOBJECT,  line 5225 of ./Sources/Core/PythonEngine.pas
  $00401C68  TPYTHONENGINE__EXECSTRING,  line 5210 of ./Sources/Core/PythonEngine.pas
  $0007C590  TEST_CODE_$$_init$,  line 51 of test_code.pas
  $0004B350
Exception at 00402708: EPyImportError:
ImportError: /usr/local/lib/python3.7/dist-packages/psycopg2/_psycopg.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: PyExc_SystemError.
```

**Comment by Alexey-T** [comment]
seems you used wrong .so file. Try to find all *python37*.so*" files and use another one for PythonEngine.

**Comment by JacoFourie** [comment]
@Alexey-T when you say wrong .so file what do you mean. I did a Find on the P and only found that one .so file. If I run simple print("Hallo World") and import other packages it works fine.

**Comment by Alexey-T** [comment]
@pyscripter Can you help here, please?

**Comment by JacoFourie** [comment]
If I do a Google search I find that this error is coming from embedding Python.

This error is in C not Lazarus but it is a similar error.

https://stackoverflow.com/questions/11842920/undefined-symbol-pyexc-importerror-when-embedding-python-in-c

**Comment by JacoFourie** [comment]
Mmmmm I get similar errors if I import numpy. So I am doing something wrong. 

Original error was: /usr/lib/python3/dist-packages/numpy/core/_multiarray_umath.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: PyNumber_Negative

[FORMS.PP] ExceptionOccurred 
  Sender=EPyImportError
  Exception=ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using ),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: /usr/lib/python3/dist-packages/numpy/core/_multiarray_umath.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: PyNumber_Negative

  Stack trace:
  $00402728  TPYTHONENGINE__RAISEERROR,  line 5452 of ./Sources/Core/PythonEngine.pas
  $00407CF0  TPYTHONENGINE__CHECKERROR,  line 6459 of ./Sources/Core/PythonEngine.pas
  $00401EEC  TPYTHONENGINE__RUN_COMMANDASOBJECTWITHDICT,  line 5259 of ./Sources/Core/PythonEngine.pas
  $00401D38  TPYTHONENGINE__RUN_COMMANDASOBJECT,  line 5225 of ./Sources/Core/PythonEngine.pas
  $00401C88  TPYTHONENGINE__EXECSTRING,  line 5210 of ./Sources/Core/PythonEngine.pas
  $0007C5B0  TEST_CODE_$$_init$,  line 53 of test_code.pas
  $0004B350
Exception at 00402728: EPyImportError:
ImportError:

**Comment by JacoFourie** [comment]
If I run the simple code in Python then it works.

pi@PI4:~/Lazarus/Projects/PythonCode $ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> a = np.arange(15).reshape(3, 5)
>>> a
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
>>>

But if I embed it in Lazarus when I got to the line  import numpy as np it will fail with the error above.

**Comment by JacoFourie** [comment]
Here is the little test program

```
unit test_code;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, Forms, Controls, Graphics, Dialogs, PythonEngine, dynlibs;

//type

  { TForm1 }

  //TForm1 = class(TForm)
  //  PythonEngine1: TPythonEngine;
  //private
  //
  //public
  //
  //end;

var
  //Form1: TForm1;
  PythonEngine1    :TPythonEngine;
  python_code      :string;

implementation

{$R *.lfm}
begin

   MaskFPUExceptions(True);
   PythonEngine1 := TPythonEngine.Create(Nil);
   PythonEngine1.DllName := 'libpython3.7.so';
   PythonEngine1.DllPath := '/usr/lib/python3.7/config-3.7m-arm-linux-gnueabihf/';
   PythonEngine1.FatalAbort := False;
   PythonEngine1.AutoLoad := True;
   PythonEngine1.LoadDll;

   if PythonEngine1.IsHandleValid then begin


      python_code := 'import traceback' + LineEnding +
                     'import time'  + LineEnding +
                     'import os'  + LineEnding +
                     'import sys'  + LineEnding +
                     'os.system(''clear'')'  + LineEnding +
                     'print(sys.version)'
                     ;

      PythonEngine1.ExecString(python_code);

   end;

   halt;

end.
```

This is the output so I now that Python is working.

3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0]
pi@PI4:~/Lazarus/Projects/PythonCode $ 


But I am not sure if I am doin something wrong to make some of the imports fail.

**Comment by Alexey-T** [comment]
did you try to adjust `sys.path`?
CudaText does it here:

```
procedure TAppPython.SetPath(const Dirs: array of string; DoAdd: boolean);
var
  Str, Sign: string;
  i: Integer;
begin
  Str:= '';
  for i:= 0 to Length(Dirs)-1 do
    Str:= Str + 'r"' + Dirs[i] + '",';
  if DoAdd then
    Sign:= '+='
  else
    Sign:= '=';
  Str:= Format('sys.path %s [%s]', [Sign, Str]);

  Exec(Str+';print("Python %d.%d.%d"%sys.version_info[:3])');
end;
```

it passes 2 dirs there:

  SetLength(Dirs, 2);
  Dirs[0]:= dir+ChangeFileExt(UiOps.PyLibrary, 'dlls');
  Dirs[1]:= dir+ChangeFileExt(UiOps.PyLibrary, '.zip');

**Comment by Alexey-T** [comment]
Ie it gives there 2 paths

- path of 'python37.zip' file
- path of 'dlls` which contains Python *.PYD files (DLLs on windows)

**Comment by JacoFourie** [comment]
@Alexey-T do I need to add this procedure to my test code? Sorry I am not sure I understand what I need to do.

**Comment by Alexey-T** [comment]
- it was a handler of TPythonEngine.OnAfterInit (the event)
- it adds (by running the small script) some paths to Python's `sys.path` (module sys of Python)

**Comment by JacoFourie** [comment]
Well Python is working as you can see. But not all the imports work. Can you import Numpy on your end?

**Comment by JacoFourie** [comment]
@Alexey-T can you simulate the error on your end by copying my code and importing numpy?

**Comment by Alexey-T** [comment]
I didn't test, yet.
the error

Sender=EPyImportError
  Exception=ImportError: /usr/local/lib/python3.7/dist-packages/psycopg2/_psycopg.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: PyExc_SystemError

means that binary .so file (with underscore in the 1st char of filename) cannot be loaded.

**Comment by Alexey-T** [comment]
I see that CudaText (uses python-for-lazarus) on python 3.8 can load numpy!
![numpy](https://user-images.githubusercontent.com/4154978/160684122-569f051e-0f3f-4699-95ee-2424cb90d385.png)

**Comment by JacoFourie** [comment]
OK but that is inside a GUI form using the GUI controls. I will try it on Linux also.

**Comment by JacoFourie** [comment]
Getting the same error on Ubuntu using GUI forms. What am I doing wrong?

Here you can see the code the properties and the error

![image](https://user-images.githubusercontent.com/17771641/160716319-f18a7c52-dcc3-4bd0-a326-eb14412e0554.png)

**Comment by JacoFourie** [comment]
So it seems what you said about sys.path is on the correct track. If I use the command sys.path I get nothing back and even if I set it using 

sys.path = ['/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/ubuntu/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']

It seems it is not saved

**Comment by JacoFourie** [comment]
How do you set sys.path using the controls. The code you have above calls 

Exec(Str+';print("Python %d.%d.%d"%sys.version_info[:3])');

So it seems you are passing parameters to the Python exe.

**Comment by JacoFourie** [comment]
OK I had to print the path in the control. The path is 100% the same as Python it self

![image](https://user-images.githubusercontent.com/17771641/160725241-12161b9a-be83-43eb-9f9c-63a52fceda1a.png)

**Comment by Alexey-T** [comment]
No ideas

**Comment by JacoFourie** [comment]
So why is it working for you then? Please help me. This is your control. Must I share my simple project. You can see it all in that image.

**Comment by Alexey-T** [comment]
first, check this project. does it work for you?
https://github.com/Alexey-T/Python-for-Lazarus/tree/master/demos_lazarus/Python_Console

**Comment by JacoFourie** [comment]
OK great. I have the sample working on Ubuntu and Raspberry Pi. Now I have a point to work from thank you.

![image](https://user-images.githubusercontent.com/17771641/160782745-d25ca90c-da68-4d38-b99a-1709b8b32147.png)

![image](https://user-images.githubusercontent.com/17771641/160782796-b246c211-bbdb-4efd-b24e-ea9de40c18fe.png)

**Comment by Alexey-T** [comment]
Compare the good demo with your demo, what is missed?

**Comment by JacoFourie** [comment]
Yes I will do that thank you.
