### ISSUE TITLE
Availability of the latest version on Lazarus Online Package manager and differences with Python4Delphi

### ISSUE THREAD

**Issue by acaland** [Alexey-T/Python-for-Lazarus#43]
Hello,

If I try to install the package through the Online Package Manager built-in in Lazarus, I see I can install the version 1.4.0, while here you use a different release number. Are the one there synced with this repo?

What are the differences between Python4Delphi and Python4Lazarus? In the wiki page of Python4Lazarus you stated the P4D supports FPC/Lazarus too. What is the latest one for Lazarus/MacOS  ?

thank you!

**Comment by Alexey-T** [comment]
Minor changes here and there. and missed last patches from P4D.
