### ISSUE TITLE
Unfreed memory blocks: 80

### ISSUE THREAD

**Issue by kjteng** [Alexey-T/Python-for-Lazarus#46]
Thank you for creating python4Lazarus. I have succesfully installed it with lazarus ver 1.2.6 and able to run python script with no major issue. 
However, I noticed that there is always some unfreed memory block whenever I use tpythonDelphivar in my apps. This error even occurs when there are only a TpythoneEngine and pythonDelphiVer in a blank form (without addtional code).  What can I do to free all the memory?
![Untitled](https://github.com/Alexey-T/Python-for-Lazarus/assets/43010410/b9aedc87-9acb-42d3-96c0-65d0de1ea14b)

**Comment by kjteng** [comment]
I think I found a temp solution: just call finalize when the pythonDelphivar is destroy (see code follow). Please confirm if this is OK. TQ.
destructor TEngineClient.Destroy;
begin
  Engine := nil; // This detaches the client from the Engine.
  if Assigned( FOnDestroy ) then
    FOnDestroy( Self );
  Finalize; //inserted by kjteng
  inherited;
end;

**Comment by kjteng** [comment]
I think I have found the cause:  TPythonDelphiVar.finalize wasnt called when it is destroyed/freed. I think we might need to add finalise as follow but I am not sure whether this is the correct way. Please confirm. TQ.
destructor TEngineClient.Destroy;
begin
  Engine := nil; // This detaches the client from the Engine.
  if Assigned( FOnDestroy ) then
    FOnDestroy( Self );
  Finalize; //added by kjteng
  inherited;
end;

**Comment by Alexey-T** [comment]
Can you look into Python for Delphi? Does it have finalise? Can you ask it’s author in GitHub issues.
